include: package:flutter_lints/flutter.yaml


linter:
  rules:
   - prefer_const_constructors
   - prefer_const_declarations
   - avoid_print
   - use_key_in_widget_constructors
   - always_use_package_imports
